encoding: UTF-8

###########
# site.title, site.url, site.author.name

title:   'Codeleft'
path:    /codeleft
url:     'http://johhoi.github.io/codeleft'
author:
  name:  'Codeleft'

#######
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
